CREATE DATABASE IF NOT EXISTS `tour_du_lich` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `tour_du_lich`;

-- Tạo bảng tbldestination
CREATE TABLE IF NOT EXISTS `tbldestination` (
  `Dest_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Dest_Name` varchar(255) NOT NULL,
  PRIMARY KEY (`Dest_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Thêm dữ liệu mẫu vào tbldestination
INSERT INTO `tbldestination` (`Dest_ID`, `Dest_Name`) VALUES
(1, 'Cần Thơ'),
(2, 'An Giang'),
(3, 'Cà Mau'),
(4, 'Bến Tre'),
(5, 'Kiên Giang'),
(6, 'Đồng Tháp'),
(7, 'Tiền Giang'),
(8, 'Vĩnh Long');

-- Tạo bảng tbtourcategory
CREATE TABLE IF NOT EXISTS `tbtourcategory` (
  `Cat_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Cat_Name` varchar(255) NOT NULL,
  `Cat_Slug` varchar(255) NOT NULL,
  PRIMARY KEY (`Cat_ID`),
  UNIQUE KEY `Cat_Slug` (`Cat_Slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Thêm dữ liệu mẫu vào tbtourcategory
INSERT INTO `tbtourcategory` (`Cat_ID`, `Cat_Name`, `Cat_Slug`) VALUES
(1, 'Chợ Nổi', 'chop-noi'),
(2, 'Rừng Tràm', 'rung-tram'),
(3, 'Biển Đảo', 'bien-dao'),
(4, 'Miệt Vườn', 'miet-vuon'),
(5, 'Tour Ngắn Ngày', 'tour-ngan-ngay');

-- Tạo bảng tbtour
CREATE TABLE IF NOT EXISTS `tbtour` (
  `Tour_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Cat_ID` int(11) DEFAULT NULL,
  `Dest_ID` int(11) DEFAULT NULL,
  `ten_tour` varchar(255) NOT NULL,
  `Tour_Image` varchar(255) DEFAULT NULL,
  `thoi_gian` varchar(100) DEFAULT NULL,
  `Price_Adult` decimal(10,0) NOT NULL,
  `Duration` varchar(100) DEFAULT NULL,
  `Vehicle` varchar(100) DEFAULT NULL,
  `Description` text DEFAULT NULL,
  `trang_thai` varchar(50) DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`Tour_ID`),
  KEY `Cat_ID` (`Cat_ID`),
  KEY `Dest_ID` (`Dest_ID`),
  CONSTRAINT `fk_tour_cat` FOREIGN KEY (`Cat_ID`) REFERENCES `tbtourcategory` (`Cat_ID`) ON DELETE SET NULL,
  CONSTRAINT `fk_tour_dest` FOREIGN KEY (`Dest_ID`) REFERENCES `tbldestination` (`Dest_ID`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Thêm dữ liệu mẫu vào tbtour
INSERT INTO `tbtour` (`Tour_ID`, `Cat_ID`, `Dest_ID`, `ten_tour`, `Tour_Image`, `thoi_gian`, `Price_Adult`, `Duration`, `Vehicle`, `Description`, `trang_thai`) VALUES
(1, 1, 1, 'Combo Cần Thơ — Chợ nổi hai ngày', 'images/1.jpg', '2 Ngày 1 Đêm', 4990000, '2 Ngày 1 Đêm', 'Xe du lịch, Tàu thuyền', 'Khám phá Cần Thơ gạo trắng nước trong...', 'active'),
(2, 2, 2, 'Rừng tràm Trà Sư - Châu Đốc', 'images/2.jpg', '1 Ngày', 1500000, '1 Ngày', 'Xe du lịch', 'Hành trình xanh ngát tại rừng tràm Trà Sư...', 'active'),
(3, 3, 3, 'Khám phá Đất Mũi Cà Mau', 'images/3.jpg', '3 Ngày 2 Đêm', 6500000, '3 Ngày 2 Đêm', 'Xe du lịch, Cano', 'Đến với điểm cực Nam của Tổ quốc...', 'active');

-- Tạo bảng tblcustomer
CREATE TABLE IF NOT EXISTS `tblcustomer` (
  `Cu_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Cu_Name` varchar(255) NOT NULL,
  `Cu_Email` varchar(255) NOT NULL,
  `Cu_Phone` varchar(50) NOT NULL,
  `Cu_Password` varchar(255) NOT NULL,
  `role` varchar(50) DEFAULT 'customer',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`Cu_ID`),
  UNIQUE KEY `Cu_Email` (`Cu_Email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Thêm admin mặc định (Mật khẩu: 123456)
-- Hash password generated by password_hash('123456', PASSWORD_DEFAULT)
INSERT INTO `tblcustomer` (`Cu_Name`, `Cu_Email`, `Cu_Phone`, `Cu_Password`, `role`) VALUES
('Quản Trị Viên', 'admin@dulichtaynambo.vn', '0123456789', '$2y$10$eE/.93/1lYgE/sKInR.YxOF25977z28LInpT/2z6yJ.tV2m67qXoW', 'admin');
